### ISSUE TITLE
☂️ Cron jobs should run as Kubernetes Cron Jobs

### ISSUE THREAD

**Issue by ibuys** [edgi-govdata-archiving/web-monitoring-processing#376]
## Expected Behavior

Current static instance should be imported into the Kubernetes cluster. All current cron jobs on the instance should be migrated to Docker instances.

The following jobs are being worked on:

- [ ] `10 * * * * /home/ubuntu/web-monitoring-versionista-scraper/cron-archiver.sh versionista2 3 2>> /var/log/cron-versionista2.log`

- [ ] `45 10 * * TUE /home/ubuntu/web-monitoring-versionista-scraper/cron-tracking-team-db.sh versionista1 186.75 6.75 2>> /var/log/cron-versionista-db-sheets.log`

- [x] `0 0 * * * /home/ubuntu/etl-tools/cron-ia-healthcheck.sh >> /var/log/cron-ia-healthcheck.log 2>&1`

- [x]  `30 3 * * * /home/ubuntu/etl-tools/cron-ia-import.sh >> /var/log/cron-ia-import.log 2>&1`

**Comment by ibuys** [comment]
Currently working on "ia-healthcheck".

**Comment by ibuys** [comment]
ia-healthcheck and ia-import are working.

**Comment by Mr0grog** [comment]
Awesome! Are there going to be PRs in web-monitoring-ops and/or here for these?
